apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: keycloak
        tier: backend
        track: stable
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:latest
        ports:
          - name: http
            containerPort: 8080
        env: 
          - name: KEYCLOAK_USER
            value: admin
          - name: KEYCLOAK_PASSWORD
            value: admin
          - name: DB_VENDOR
            value: h2
          - name: KEYCLOAK_IMPORT
            value: /tmp/realm-export-sevyhauth.json 
        volumeMounts:
        - name: realm-config
          mountPath: "/tmp"
        resources:
          limits:
            memory: "1000Mi"
            cpu: "800m"
          requests:
            memory: "500Mi"
            cpu: "500m"
        
      volumes:
      - name: realm-config
        configMap:
          name: realm-config
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: keycloak-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keycloak
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
