apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
        tier: backend
        track: stable
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:latest
        ports:
          - name: http
            containerPort: 8080
        env: 
          - name: KEYCLOAK_USER
            value: admin
          - name: KEYCLOAK_PASSWORD
            value: admin
          - name: DB_VENDOR
            value: h2
          - name: KEYCLOAK_IMPORT
            value: /tmp/realm-export-sevyhauth.json 
        volumeMounts:
        - name: realm-config
          mountPath: "/tmp"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
          requests:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: realm-config
        configMap:
          name: realm-config
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  type: LoadBalancer
