apiVersion: apps/v1
kind: Deployment
metadata:
  name: sevyh-chatservice-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sevyh-chatservice
  template:
    metadata:
      labels:
        app: sevyh-chatservice
    spec:
      containers:
      - name: sevyh-chatservice
        image: jjuless/sevyhchatservice:latest
        ports:
        - containerPort: 3001
        env:
        - name: CASSANDRA_HOST
          value: cassandra-service
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq-clusterip-srv
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        
---
apiVersion: v1
kind: Service
metadata:
  name: sevyh-chatservice
spec:
  type: ClusterIP
  selector:
    app: sevyh-chatservice
  ports:
  - name: sevyh-chatservice-port
    protocol: TCP
    port: 3001
    targetPort: 3001
