apiVersion: apps/v1
kind: Deployment
metadata:
  name: sevyh-userbackend
spec:
  selector:
    matchLabels:
      app: user-backend
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: user-backend
        tier: backend
        track: stable
    spec:
      containers:
      - name: sevyh-userservice
        image: jjuless/sevyhuserservice:latest
        ports:
        - name: http
          containerPort: 3003
        env:
        - name: KEYCLOAK_AUTH-SERVER-URL
          value: http://keycloak.default.svc.cluster.local:8080/auth
        - name: KEYCLOAK_CREDENTIALS_SECRET
          value: verysecret
        resources:
          limits:
            memory: "300Mi"
            cpu: "400m"
          requests:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: sevyh-userbackend
spec:
  selector:
    app: user-backend
    tier: backend
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sevyh-userbackend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sevyh-userbackend
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
