apiVersion: apps/v1
kind: Deployment
metadata:
  name: sevyh-frontend
spec:
  selector:
    matchLabels:
      app: sevyh
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: sevyh
        tier: frontend
        track: stable
    spec:
      containers:
      - name: sevyh-frontendservice
        image: jjuless/sevyh-front-end:latest
        env:
          - name: VITE_KEYCLOAK_URL
            value: http://keycloak.default.svc.cluster.local:8080/auth
          - name: VITE_USERSERVICE_URL
            value: http://sevyh-userservice.default.svc.cluster.local:3003/api
          - name: VITE_CHATSERVICE_URL
            value: http://sevyh-chatservice.default.svc.cluster.local:3001/api
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        
---
apiVersion: v1
kind: Service
metadata:
  name: sevyh-frontend
spec:
  selector:
    app: sevyh
    tier: frontend
  ports:
  - protocol: TCP
    port: 3004
    targetPort: 80
  type: LoadBalancer