apiVersion: apps/v1
kind: Deployment
metadata:
  name: sevyh-chatbackend
spec:
  selector:
    matchLabels:
      app: chat-backend
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: chat-backend
        tier: backend
        track: stable
    spec:
      containers:
      - name: sevyh-chatservice
        image: jjuless/sevyhchatservice:latest
        ports:
        - name: http
          containerPort: 3001
        env:
        - name: CASSANDRA_HOST
          value: cassandra-service
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq-clusterip-srv

        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        
---
apiVersion: v1
kind: Service
metadata:
  name: sevyh-chatbackend
spec:
  selector:
    app: chat-backend
    tier: backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: LoadBalancer
